### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by sbkirby** [jeffbass/imagehub#3]
This following error occurs with Windows 10: 
```
Traceback (most recent call last):
  File "imagehub\imagehub\imagehub.py", line 41, in main
    with Patience(hub.patience):
  File "C:\Stephens_Folder\Programming\Home_Monitor\imagehub\imagehub\tools\utils.py", line 63, in __enter__
    signal.signal(signal.SIGALRM, self.raise_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
2020-08-05 08:31:47,888 ~ Exiting imagehub.py
```
A work-around (**not a fix**) for this error can be made to `utils.py`.  Add the following line of code to the import section of utils.py.

`from sys import platform`

Next, replace the `__enter__` and `__exit__` functions of `class Patience` section with the following:
```
    def __enter__(self):
        if platform != "win32":
            signal.signal(signal.SIGALRM, self.raise_timeout)
            signal.alarm(self.seconds)
        else:
            pass

    def __exit__(self, *args):
        if platform != "win32":
            signal.alarm(0)    # disable alarm
        else:
            pass

```
Note: This will allow you to run `imagehub.py` on a Windows platform, but it will not function as a normal, and may result in some unusual behavior of the `imagehub`.

**Comment by jeffbass** [comment]
Thanks for this bug report. I want to support Windows users and will need to remove references to the unix / Linux SIGALRM from the utils.py module. The SIGALRM unix OS signal is a simple timer, but it runs asynchronously outside of Python. I will need to replace it with another algorithm. I suspect I need to get rid of the need for the Patience class entirely.

I should have a fix for this in a few days. Your work-around removes the timer function, which should work fine until then.

**Comment by jeffbass** [comment]
FYI, the Patience timer function is used in only 1 place in `imagehub.py` -- in the receive images loop in `main().` It's purpose is to raise an exception if the **imagehub** does not receive a message from any **imagenode** for a patience amount of time in minutes (as set in the yaml settings). The `Patience.Timeout` exception just logs the lack of **imagenode** messages and then the receive images loop continues. I put it there to alert me to a possible network outage or other problem affecting communications from **imagenodes** to an **imagehub**. I typically set it to 60 (minutes). I will change the `main()` loop to make the `Patience.Exception` test unnecessary. I will produce the "too much time between imagenode messages" log message using a different algorithm that does not use `signal.SIGALRM`.

**Comment by jeffbass** [comment]
Hi @sbkirby,
I coded a fix for this and pushed it to the master branch. Patience class is gone and there are no further references to signal.SIGALRM. Tested OK on Macs and Linux machines. But I don't have a Windows computer.
Could you let me know if it now works on your Windows machine without the work-around?
Thanks,
Jeff

**Comment by sbkirby** [comment]
Hey @jeffbass,
I've tested the new version on Windows 10 for several days, and it appears to be fine.  I'm going to close this issue.
Thanks for your help.
Stephen

**Comment by jeffbass** [comment]
Thanks!
